// angular-studies/src/app/app.ts
import { Component, signal } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { Greeting } from './components/greeting/greeting';
import { Card } from './components/card/card';
import { Counter } from './components/counter/counter';
import { TextMirror } from './components/text-mirror/text-mirror';
import { SumList } from './components/sum-list/sum-list';
import { RenderingList } from './components/rendering-list/rendering-list';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, Greeting, Card, Counter, TextMirror, SumList, RenderingList],
  templateUrl: './app.html',
  styleUrl: './app.scss'
})
export class App {
  protected readonly title = signal('angular-studies');
}

// react-studies/src/App.tsx
import { Greeting } from './components/Greeting';
import { Card } from './components/Card';
import { Counter } from './components/Counter';
import { TextMirror } from './components/TextMirror';
import { SumList } from './components/SumList';
import { RenderingList } from './components/RenderingList';

function App() {
  return (
    <>
      <Greeting name= "Gabriel"/>
      <Card title= "Card Title">
        <p>child prop number 1</p>
      </Card>
      
      <Card title= "Card Title 2">
        <ul>
          <li>child list number 1</li>
          <li>child list number 2</li>
        </ul>
      </Card>

      <Counter/>

      <TextMirror/>

      <SumList/>

      <RenderingList/>
    </>
  )
}

export default App
